
-- -- Groups table (tenant-level group definitions)
-- CREATE TABLE IF NOT EXISTS groups (
--     tenant_id TEXT(50) NOT NULL,
--     group_id TEXT(255) NOT NULL,
--     group_display_name TEXT(255) NOT NULL,
--     group_description TEXT(500),
--     group_type TEXT(100) NOT NULL, -- Security, Microsoft 365, etc.
--     mail_enabled INTEGER NOT NULL DEFAULT 0,
--     security_enabled INTEGER NOT NULL DEFAULT 1,
--     mail_nickname TEXT(100),
--     visibility TEXT(50) DEFAULT 'Private',
--     member_count INTEGER NOT NULL DEFAULT 0,
--     owner_count INTEGER NOT NULL DEFAULT 0,
--     created_at TEXT NOT NULL DEFAULT (datetime('now')),
--     last_updated TEXT NOT NULL DEFAULT (datetime('now')),
--     PRIMARY KEY (tenant_id, group_id)
-- );

-- -- User groups table V2 (user-group assignments)
-- CREATE TABLE IF NOT EXISTS user_groupsV2 (
--     user_id TEXT(50) NOT NULL,
--     tenant_id TEXT(50) NOT NULL,
--     group_id TEXT(255) NOT NULL,
--     user_principal_name TEXT(255) NOT NULL,
--     group_display_name TEXT(255) NOT NULL,
--     group_type TEXT(100) NOT NULL,
--     membership_type TEXT(50) DEFAULT 'Member', -- Member, Owner, Guest
--     created_at TEXT NOT NULL DEFAULT (datetime('now')),
--     last_updated TEXT NOT NULL DEFAULT (datetime('now')),
--     PRIMARY KEY (user_id, tenant_id, group_id)
-- );

-- -- Indexes for performance
-- CREATE INDEX IF NOT EXISTS idx_groups_tenant ON groups(tenant_id);
-- CREATE INDEX IF NOT EXISTS idx_groups_type ON groups(group_type);
-- CREATE INDEX IF NOT EXISTS idx_user_groupsV2_tenant ON user_groupsV2(tenant_id);
-- CREATE INDEX IF NOT EXISTS idx_user_groupsV2_user ON user_groupsV2(user_id);
-- CREATE INDEX IF NOT EXISTS idx_user_groupsV2_group ON user_groupsV2(group_id);
